### ISSUE TITLE
Fix language data

### ISSUE THREAD

**Issue by shvrm** [shvrm/Languages#1]
@ramyaragupathy can we fix the following:
- markers: should only be in locations where we have physical offices (SF, DC, BLR, AYA, BER)
- languages: languages spoken by those working remotely should be folded into the DC office
- english: add english as a language, and highlight all countries where english is the official language

**Comment by ramyaragupathy** [comment]
> - markers: should only be in locations where we have physical offices (SF, DC, BLR, AYA, BER)
> - languages: languages spoken by those working remotely should be folded into the DC office

^^ requires two changes to  [`mbxLanguages.json`](https://github.com/shvrm/Languages/blob/master/mbxLanguages.json) file.
- [x] add the languages from the remote locations to DC office
- [x] remove the remote office locations from the list

@shvrm Want to give it a spin?

**Comment by shvrm** [comment]
Wrapped this up today w/ @ramyaragupathy. No next actions!
