### ISSUE TITLE
Fix Country/Language Count

### ISSUE THREAD

**Issue by shvrm** [shvrm/Languages#2]
- Total Number of unique languages spoken at Mapbox: 22
- Countries where these languages are official: 110

....but we're getting the following matches on the map which doesn't seem to add up to the ^^
- Ayacucho Peru - 21 countries
- San Francisco, California - 84 countries
- Washington, D.C. - 115 countries
- Berlin, Germany - 47 countries
- Bangalore, India - 30 countries

cc: @ramyaragupathy

**Comment by ramyaragupathy** [comment]
@shvrm  Removed duplicates from country filter as part of https://github.com/shvrm/Languages/commit/fa417a67d1ea5dc3986fafbb076ddaec9b3380a7.
 Now, the count for each office matches with QGIS query results.

> A total of 100 matches found for Mapbox, DC
> A total of 73 matches found for Mapbox, San Francisco
> A total of 44 matches found for Mapbox, Berlin
> A total of 26 matches found for Mapbox, Bengaluru
> A total of 21 matches found for Mapbox, Peru

Also, total number of unique languages spoken at Mapbox: 24
1. SPN
2. GRC
3. GER
4. ITA
5. CAN
6. CHN
7. FRN
8. JPN
9. VIT
10. GHA
11. TWI
12. ARA
13. POR
14. RUS
15. DUT
16. LAT
17. HIN
18. UKR
19. MAN
20. TAM
21. MAL
22. GUJ
23. BEN
24. FLP
