### ISSUE TITLE
Information Box

### ISSUE THREAD

**Issue by shvrm** [shvrm/Languages#3]
@ramyaragupathy - let's get an information box on the map (similar to railway map). To start, this should contain some boiler text - 

---

Later this month we'll be opening up our fifth, and newest office in Berlin, Germany. This brings our team size to a total of xxx individuals. 

Last week we did a quick poll of all the languages spoken by our team across offices. In total we speak 22 languages that are official/co-official to 110 countries. Hover over our office locations to find out the global reach of our team based on our language repotoire.

[Meet our team]()
[Join our team]()

**Comment by ramyaragupathy** [comment]
Info bar added through commit https://github.com/shvrm/Languages/commit/1cad62bcebe95cca13af0c5d29096e5d5cd57d58.
